blank_issues_enabled: false
contact_links:
  name: Ask a question or get support
  url: https://www.google.com/search?q=https://github.com/aaditya-dubey09/devodyssey/discussions
  about: Please use discussions for general questions or setup help, not bug reports or feature requests.
